project:
  type: website

website:
  title: "<b>Claudiu Forgaci</b>"
  navbar:
    right:
      # - href: index.qmd
      #   text: Home
      - about.qmd
      - href: publications.qmd
        text: Publications
      - href: presentations.qmd
        text: Presentations
      - href: software.qmd
        text: Software
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Website under construction"
    type: primary
    position: below-navbar

format:
  html:
    theme:
      - simplex
      # - brand
    css: styles.css
    toc: true



